'use client'
import {useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,Plus,Trash2,Save,Film} from 'lucide-react'
const starter=[]
export default function Admin(){
 const [ok,setOk]=useState(false); const [movies,setMovies]=useState([]); const [form,setForm]=useState({title:'',year:'',genre:'Drama',rating:'',description:'',embed:''})
 function login(e){e.preventDefault();if(e.target.password.value===process.env.NEXT_PUBLIC_ADMIN_PASSWORD||e.target.password.value==='openfilm-admin'){setOk(true)}}
 function add(e){e.preventDefault();if(!form.title||!form.year)return;const m={...form,id:form.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+form.year};const next=[...movies,m];setMovies(next);localStorage.setItem('openfilm-movies',JSON.stringify(next));setForm({title:'',year:'',genre:'Drama',rating:'',description:'',embed:''})}
 function remove(id){const next=movies.filter(m=>m.id!==id);setMovies(next);localStorage.setItem('openfilm-movies',JSON.stringify(next))}
 if(!ok)return <main className="adminPage"><Link href="/" className="back"><ArrowLeft/> Back to OpenFilm</Link><div className="login"><div className="adminIcon"><Film/></div><h1>Admin Studio</h1><p>Manage your movie catalog and authorized embeds.</p><form onSubmit={login}><input name="password" type="password" placeholder="Admin password" required/><button>Enter dashboard</button></form><small>Change the demo password in production before publishing.</small></div></main>
 return <main className="adminPage"><div className="adminTop"><Link href="/" className="brand"><span>O</span> OPENFILM</Link><Link href="/">View site ↗</Link></div><div className="dashboard"><div><span className="kicker">CONTENT MANAGEMENT</span><h1>Movie catalog</h1><p>Add movies and their authorized embed URLs. Changes are stored in this browser for the MVP.</p></div><form className="movieForm" onSubmit={add}><h2><Plus/> Add a movie</h2><div className="formGrid"><input placeholder="Movie title *" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Year *" type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><input placeholder="Genre" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/><input placeholder="Rating (e.g. 7.8)" value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})}/></div><textarea placeholder="Short SEO description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Authorized embed / iframe URL" value={form.embed} onChange={e=>setForm({...form,embed:e.target.value})}/><button className="save"><Save/> Save movie</button></form><div className="adminList"><h2>Your added movies <span>{movies.length}</span></h2>{movies.map(m=><div className="adminMovie" key={m.id}><div><b>{m.title}</b><small>{m.year} • {m.genre} • {m.embed?'Embed ready':'No embed yet'}</small></div><button onClick={()=>remove(m.id)}><Trash2/></button></div>)}{!movies.length&&<div className="adminEmpty">No custom movies yet.</div>}</div></div></main>
}